---

obter ingredientes do bolo:

script:

- mkdir build
- cd build
- touch bolo.txt 
- echo "2 xícaras de açúcar" > bolo.txt
- echo "2 colheres de manteiga" > bolo.txt
- echo "3 ovos" > bolo.txt
- echo "1 xícara de leite" > bolo.txt
- echo "1 colher de sopa de fermento" > bolo.txt


verificar lista de ingredientes:
script:

- NOME_ARQ=bolo.txt
- test -f build/$NOME_ARQ
- cd build
- grep "farinha de trigo" $NOME_ARQ
- grep "açúcar" $NOME_ARQ
- grep "manteiga" $NOME_ARQ
- grep "ovos" $NOME_ARQ
- grep "leite" $NOME_ARQ
- grep "fermento" $NOME_ARQ 